#!/bin/bash

image_registry_url=$(az keyvault secret show --name image-registry-url --subscription thejameshome --vault-name cloud-operations-vault --query value --output tsv)
image_registry_username=$(az keyvault secret show --name image-registry-username --subscription thejameshome --vault-name cloud-operations-vault --query value --output tsv)
image_registry_password=$(az keyvault secret show --name image-registry-password --subscription thejameshome --vault-name cloud-operations-vault --query value --output tsv)

weather_bit_api_url=$(az keyvault secret show --name weather-bit-api-url --subscription thejameshome --vault-name cloud-operations-vault --query value --output tsv)
weather_bit_api_key=$(az keyvault secret show --name weather-bit-api-key --subscription thejameshome --vault-name cloud-operations-vault --query value --output tsv)

cd ~

#docker login $image_registry_url -u $image_registry_username -p $image_registry_password

kubectl config use-context weatherwatch-api

kubectl delete secret weatherwatch-api-secret --ignore-not-found

kubectl create secret docker-registry weatherwatch-api-secret \
	--docker-server=$image_registry_url \
	--docker-username=$image_registry_username \
	--docker-password=$image_registry_password

rm weatherwatch-api-deployment.yaml
cat <<EOF | tee weatherwatch-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherwatch-api-deployment
  labels:
    app: weatherwatch-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherwatch-api
  template:
    metadata:
      labels:
        app: weatherwatch-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "weatherwatch-api"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: weatherwatch-api
        image: weatherwatch.azurecr.io/weatherwatch-api
        env:
        - name: WEATHER_BIT_API_URL
          value: $weather_bit_api_url
        - name: WEATHER_BIT_API_KEY
          value: $weather_bit_api_key 
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: weatherwatch-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: weatherwatch-api
spec:
  selector:
    app: weatherwatch-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
EOF

kubectl delete -f weatherwatch-api-deployment.yaml --ignore-not-found

kubectl apply -f weatherwatch-api-deployment.yaml

kubectl get pods
kubectl get services

